class EnquiryModalData {
  String enqFname;
  String enqLname;
  String empId;
  String enqPhn;
  String enqEmail;
  int gender;
  int occupation;
  String enqDOb;
  int enqPincode;
  String enqDist;
  String enqState;
  String enqUid;
  String status;
  DateTime dateTime;
  String vehicleDetails;
  String variant;
  String carColor;
  String bookingDate;

  EnquiryModalData(
      {required this.empId,
      required this.enqUid,
      required this.enqDOb,
      required this.enqDist,
      required this.enqEmail,
      required this.bookingDate,
      required this.carColor,
      required this.variant,
      required this.vehicleDetails,
      required this.enqFname,
      required this.enqLname,
      required this.enqPhn,
      required this.status,
      required this.enqPincode,
      required this.enqState,
      required this.dateTime,
      required this.gender,
      required this.occupation});

  // factory EnquiryModalData.parseResponse(dynamic data) {
  //   return EnquiryModalData(
  //     gender: data["id"],
  //     empId: data["id"] ?? 0,
  //     enqDOb: data["START_TIME"],
  //     enqDist: data["END_TIME"],
  //     enqEmail: data["SUBJECT_ID"],
  //     enqFname: data["SCHOOL_ID"],
  //     enqLname: data["CLASS_ID"],
  //     enqPhn: data["SECTION_ID"],
  //     enqPincode: data["START_DATE"],
  //     enqState: data["END_DATE"],
  //     occupation: data["END_DATE"],
  //   );
  // }
}

List<EnquiryModalData> getEnquiryModalData() {
  return [
    EnquiryModalData(
        empId: "MA017063",
        enqUid: "ENQ202312001",
        enqDOb: "1978/05/04",
        enqDist: "Krishna",
        enqEmail: "ranga@gmail.com",
        enqFname: "Ranga",
        enqLname: "Komma",
        bookingDate: "22-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "Alto",
        dateTime: DateTime.now(),
        enqPhn: "+91 6308529632",
        enqPincode: 520042,
        status: "Hot",
        enqState: "AP",
        gender: 1,
        occupation: 3),
    EnquiryModalData(
        empId: "MA017068",
        enqUid: "ENQ202312075",
        enqDOb: "1978/08/06",
        enqDist: "vizag",
        dateTime: DateTime.now(),
        enqEmail: "bala@gmail.com",
        enqFname: "banaga",
        enqLname: "bala",
        status: "cold",
        enqPhn: "+91 6374129632",
        enqPincode: 535006,
        bookingDate: "02-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "SwiftDezire",
        enqState: "AP",
        gender: 1,
        occupation: 2),
    EnquiryModalData(
        dateTime: DateTime.now(),
        empId: "MA017102",
        enqUid: "ENQ202312001",
        enqDOb: "1978/05/04",
        enqDist: "Krishna",
        enqEmail: "madhu@gmail.com",
        enqFname: "madhu",
        enqLname: "Gaaa",
        status: "cold",
        enqPhn: "+91 9988529632",
        enqPincode: 598542,
        bookingDate: "18-01-2023",
        carColor: "Metalic Car",
        variant: "Mxi",
        vehicleDetails: "Innova",
        enqState: "AP",
        gender: 1,
        occupation: 4),
    EnquiryModalData(
        dateTime: DateTime.now(),
        empId: "MA017230",
        enqUid: "ENQ202311098",
        enqDOb: "1990/10/04",
        enqDist: "Krishna",
        enqEmail: "hari@gmail.com",
        enqFname: "Hari",
        enqLname: "hari",
        bookingDate: "29-05-2023",
        carColor: "Naroon",
        variant: "Mxi",
        vehicleDetails: "Ertiga",
        status: "cold",
        enqPhn: "+91 9989529632",
        enqPincode: 585522,
        enqState: "AP",
        gender: 1,
        occupation: 1),
    EnquiryModalData(
        dateTime: DateTime.now(),
        empId: "MA017120",
        enqUid: "ENQ202310456",
        enqDOb: "1987/05/04",
        enqDist: "Krishna",
        status: "cold",
        enqEmail: "dinesh@gmail.com",
        enqFname: "dinesh",
        enqLname: "jara",
        enqPhn: "+91 9963529632",
        bookingDate: "22-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "Swift",
        enqPincode: 585255,
        enqState: "AP",
        gender: 1,
        occupation: 3),
    EnquiryModalData(
        empId: "MA017999",
        dateTime: DateTime.now(),
        enqUid: "ENQ202309050",
        enqDOb: "1981/04/14",
        enqDist: "Krishna",
        enqEmail: "mahesh@gmail.com",
        enqFname: "Mahesh",
        enqLname: "manchu",
        status: "warm",
        enqPhn: "+91 9985529632",
        bookingDate: "22-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "Swift",
        enqPincode: 574552,
        enqState: "AP",
        gender: 1,
        occupation: 3),
    EnquiryModalData(
        empId: "MA0170620",
        enqUid: "ENQ202312006",
        enqDOb: "1978/05/09",
        enqDist: "Krishna",
        enqEmail: "ramana@gmail.com",
        dateTime: DateTime.now(),
        enqFname: "ramana",
        status: "cold",
        bookingDate: "22-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "Swift",
        enqLname: "boddo",
        enqPhn: "+91 6308741632",
        enqPincode: 520085,
        enqState: "AP",
        gender: 2,
        occupation: 9),
    EnquiryModalData(
        empId: "MA017093",
        enqUid: "ENQ202312089",
        enqDOb: "1985/09/02",
        dateTime: DateTime.now(),
        enqDist: "Krishna",
        enqEmail: "ramesh@gmail.com",
        enqFname: "ramesh",
        status: "Hot",
        enqLname: "Ranchi",
        enqPhn: "+91 6378969632",
        bookingDate: "22-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "Swift",
        enqPincode: 535002,
        enqState: "AP",
        gender: 1,
        occupation: 1),
    EnquiryModalData(
        empId: "MA017789",
        enqUid: "ENQ202312552",
        enqDOb: "1980/08/25",
        enqDist: "vizag",
        status: "cold",
        enqEmail: "raj@gmail.com",
        enqFname: "Raj",
        enqLname: "Remma",
        bookingDate: "22-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "Swift",
        enqPhn: "+91 9708529632",
        enqPincode: 530025,
        dateTime: DateTime.now(),
        enqState: "AP",
        gender: 1,
        occupation: 6),
    EnquiryModalData(
        empId: "MA017183",
        enqUid: "ENQ202312020",
        enqDOb: "1983/05/10",
        dateTime: DateTime.now(),
        enqDist: "Vizag",
        bookingDate: "22-01-2023",
        carColor: "Red",
        variant: "Mxi",
        vehicleDetails: "Swift",
        status: "warm",
        enqEmail: "roma@gmail.com",
        enqFname: "Lakshmi",
        enqLname: "Roma",
        enqPhn: "+91 637829632",
        enqPincode: 520012,
        enqState: "AP",
        gender: 2,
        occupation: 2),
  ];
}
